# Terminal
set -g default-terminal "screen-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Index windows and panes from 1 not 0
set -g base-index 1
setw -g pane-base-index 1

# Mouse support
set -g mouse on

# Increase history
set -g history-limit 10000

# Reduce escape time
set -sg escape-time 10

# Remap prefix from ctrl+b to ctrl+a
unbind C-b
set -g prefix C-a
bind C-a send-prefix

# Reload config
bind r source-file ~/.tmux.conf \; display "Config reloaded!"

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'egel/tmux-gruvbox'

# Gruvbox theme
set -g @tmux-gruvbox 'dark256'

# Initialize TPM
run '$(brew --prefix)/opt/tpm/share/tpm/tpm'
